### ISSUE TITLE
关于域名 takemeto.icu

### ISSUE THREAD

**Issue by keainye** [PanicMaker/GoPractice#1]
你好，新年快乐！

几个月前我购买了域名 `takemeto.icu`，但无法将其解析至 GitHub Pages。打开网页发现，你的某个仓库正在使用这个域名。能否请你将它删除？十分感谢！😭

**Comment by keainye** [comment]
实在是没有在 GitHub 找到你的联系方式，所以只能以这种形式对话🙇

**Comment by PanicMaker** [comment]
等我晚上有空查一下哈

**Comment by PanicMaker** [comment]
我删除了我的Github Pages库，不知道是否与这个有关哈，你可以在试试

**Comment by keainye** [comment]
现在没问题了，十分感谢！
